# Generated by Django 5.0 on 2023-12-17 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('geography', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('form', models.CharField(max_length=50)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='country', to='OneToOneApp.country')),
            ],
        ),
    ]
